config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #set root path
  root to: "home#index"
   
  namespace :users do 
	  # dashboard for hospital 
	  get "/dashboard" => "dashboards#index"
	  post "/download_patients_data" => "dashboards#get_patient_data"
  end	  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	# associations
	has_one :user

	ROLES = ["Hospital", "Patient"]
end

app/models/user.rb
require 'csv'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associations
  belongs_to :role

  accepts_nested_attributes_for :role

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < ApplicationController

	def index
	end

	def get_patient_data
		@users = User.joins(:role).where("roles.name" => "Patient")
    respond_to do |format|
      #format.html
	    format.html
	    format.json { send_data @users.to_json , :type => 'application/json; header=present', :disposition => "attachment; filename=patients.json" }
	    format.csv { send_data @users.to_csv , filename: "patients.csv"}
    end
	end	
		
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # get roles from database
  before_action :set_roles, only: [:new, :create]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id])
  end

  def set_roles
    @roles = Role.where.not(:name => "Admin").pluck(:name, :id)
    #resource.build_role
  end  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/dashboards_helper.rb
module Users::DashboardsHelper
end

app/views/home/index.html.erb
<div class="full-width banner1"><!--start banner1-->
	<div class="bg__foo">
		<h1>A prestigious Dental Center<br />
		<span>Offering Comprehensive Dental Treatment at Al Khor, State of Qatar.</span></h1>
	</div>
	<div class="nav">
		<div class="navbar-toggle">
			<span></span>
			<span></span>
			<span></span>
		</div>
		<ul class="navigation">
			<li class="active"><a href="#">LOTUS Story</a></li>
			<li> 
        <% if !current_user %>
			    <%= link_to "Sign Up", new_user_registration_path %>
			  <% end %>  
			</li>
			<li>
			  <!-- display user email if user login -->
			  <% if current_user %>
          <%= link_to "Login as "+ current_user.email , new_user_session_path %>					  
			  <% else %>
			    <%= link_to "Login", new_user_session_path %>
			  <% end %>  				
			</li>

			<% if current_user && current_user.role.name == Role::ROLES[0] %>
				<li>
				  <%= link_to "Dashboard", users_dashboard_path %>
				</li>
			<% end %>				
			<li>
				<% if user_signed_in? %>
				  <li>
				  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
				  </li>
				<% end %>				
			</li>

		</ul>
	</div>
</div><!--end banner1-->

<div class="full-width apoointment"><!--start apoointment-->
	<a class="btn" href="#">Make an Appointment</a>
</div><!--end apoointment-->

<div class="full-width section1"><!--start section1-->
	<div class="container">
		<div class="about_img">
		<%=image_tag "/assets/about.jpg", :alt=> "about"%>
			<!-- <img src="images/about.jpg" alt="about" /> -->
		</div>
		<div class="about_content">
			<h1>Lotus Story</h1>
			<p>Our Mission to pioneer in Dentistry and Plastic care, and to attend to our responsibilities towards both of the doctor and the patient through founding the best medical environment that is constantly positive & supportive. </p>
			<a class="btn no-pad" href="#">Dicover More</a>
		</div>
	</div>
</div><!--end section1-->


<div class="full-width section3"><!--start section3-->
	<div class="container">
		<h1>Our Services</h1>
		<h4>Our dental centres offer a range of treatments, from dental examinations to specialist treatments</h4>
	</div>
	<div id="parentHorizontalTab">
		<div class="container">
			<ul class="resp-tabs-list hor_1">
				<li>
					<div class="s_icon">
					  <%=image_tag "s-1.png" %>
					 <!--  <img src="images/s-1.png" alt="services" /> -->
					</div>
					<h4>Implantology</h4>
				</li>
				<li>
					<div class="s_icon"><%=image_tag "s-2.png" %></div>
					<h4>Orthodontic</h4>
				</li>
				<li>
					<div class="s_icon"><%=image_tag "s-3.png" %></div>
					<h4>Dental Surgery</h4>
				</li>
				<li>
					<div class="s_icon"><%=image_tag "s-4.png" %></div>
					<h4>Hollywood Smile</h4>
				</li>
			</ul>
		</div>
		<div class="resp-tabs-container hor_1">
			<div class="container">
				<div class="tab_cont">
					<img src="images/pro1.png" />
					<h3>Dental Implantology Services</h3>
					<p>Implantology is the branch of dentistry that treats patients who lost one or more of their teeth, improving chewing function and speech, and also achieving better esthetics by surgically placing dental implants.</p>

					<p>Dental implants are the best supstitute for the lost teeth, because they replace and serv as natural root of the tooth.
					</p>
					<a class="btn no-pad" href="#">Explore More</a>
				</div>
			</div>
			<div class="container">
				<div class="tab_cont">
					<img src="images/pro1.png" />
					<h3>Orthodontic Implantology Services</h3>
					<p>Implantology is the branch of dentistry that treats patients who lost one or more of their teeth, improving chewing function and speech, and also achieving better esthetics by surgically placing dental implants.</p>

					<p>Dental implants are the best supstitute for the lost teeth, because they replace and serv as natural root of the tooth.
					</p>
					<a class="btn no-pad" href="#">Explore More</a>
				</div>
			</div>
			<div class="container">
				<div class="tab_cont">
					<img src="images/pro1.png" />
					<h3>Dental Surgery Implantology Services</h3>
					<p>Implantology is the branch of dentistry that treats patients who lost one or more of their teeth, improving chewing function and speech, and also achieving better esthetics by surgically placing dental implants.</p>

					<p>Dental implants are the best supstitute for the lost teeth, because they replace and serv as natural root of the tooth.
					</p>
					<a class="btn no-pad" href="#">Explore More</a>
				</div>
			</div>
			<div class="container">
				<div class="tab_cont">
					<img src="images/pro1.png" />
					<h3>Hollywood Smile Implantology Services</h3>
					<p>Implantology is the branch of dentistry that treats patients who lost one or more of their teeth, improving chewing function and speech, and also achieving better esthetics by surgically placing dental implants.</p>

					<p>Dental implants are the best supstitute for the lost teeth, because they replace and serv as natural root of the tooth.
					</p>
					<a class="btn no-pad" href="#">Explore More</a>
				</div>
			</div>
		</div>
	</div>
</div><!--end section3-->


<div class="full-width section8"><!--start section8-->
	<div class="container">
		<h1>Lotus Dental Center offering best dental treatment
		<span>at Al Khor, State of Qatar</span></h1>
		<a class="btn" href="#">Make an Appointment</a>
		<a class="btn" href="tel:97433356887">Call US . +974 3335 6887</a>
	</div>
</div><!--end section8-->

<div class="full-width footer"><!--start footer-->
	<div class="container">
		<div class="contact_us">
			<h1>Contact Us</h1>
			<p><span>Lotus Dental Center</span>
			512, City center, Opp Shukan Complex, <br />
			Sola, Ahmedabad, Gujarat 380060
			<br /><br />
			<span>Call Us:</span>
			<a class="f_call" href="tel:+090162 27777">+090162 27777</a>
			<br /><br />
			<span>Email:</span>
			<a href="mailto:info@aglowiditsolutions.com">info@aglowiditsolutions.com</a></p>
			<div class="get_social">
				<p><span>Get Social:</span></p>
				<div class="social">
					<ul>
						<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
		
<!-- 		<div class="twitter">
			<h1>Twitter</h1>
			<img class="tw" src="images/tw_img.png" />
		</div> -->
		
	</div>
	<div class="full-width footer_map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1797.98875029279!2d51.49703704847862!3d25.672040549331772!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e45f9ea13c0f6c5%3A0x6177519e7944a693!2sLOTUS+DENTAL+CENTER!5e0!3m2!1sen!2sin!4v1483447519891" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div><!--end footer-->

<div class="full-width copy_rights"><!--start copy_rights-->
	<div class="container">
		<div class="copy"><p>2016, <a href="#">Lotus Dental Center</a>. All rights reserved.</p></div>
		<div class="f_links">
			<ul>
				<li><a href="#">Contact Us</a></li>
				<li><a href="#">Media</a></li>
				<li><a href="#">Terms of Use</a></li>
				<li><a href="#">Privacy Policy</a></li>
			</ul>
		</div>
		<a href="#" class="scrollup"></a>
	</div>
</div><!--end copy_rights-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healthcare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'jquery-2-2-0' %> 
  </head>

  <body class="loading">

    <div class="wrapper">
      <div class="full-width header"><!--start header-->
        <div class="container_two">

          <div class="full-width logo">
            <%= link_to image_tag("/assets/logo.png"), root_path %>
              <!-- <img src="images/logo.png" alt="logo" width="315" height="69" /> -->
            
          </div>
        </div>
      </div><!--end header-->    
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/users/dashboards/index.html.erb
<div class="mrg-top-10">
 
  <h1 class="mrg-top-30"> Download Patients Data</h1>
 
  <div class="row text-center mrg-top-30 no_mrg">
    <div class="col-md-6">
      <%= button_to "Download CSV", users_download_patients_data_path("csv") , :class => "btn btn-primary btn-prmy-cust"%>
    </div>
    <div class="col-md-6">
      <%= button_to "Download JSON", users_download_patients_data_path("json") , :class => "btn btn-primary btn-prmy-cust"%>
    </div>    
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>